defaults: &defaults
  working_directory: ~/buildbox
  docker:
    - image: cimg/node:16.15.1

version: 2.0
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14

      - run:
          name: Login to Docker registry
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run:
          name: Build image
          command: docker build -t tanngoc93/coupon.frontend:latest .

      - run:
          name: Push image to Docker registry 
          command: docker push tanngoc93/coupon.frontend:latest

workflows:
  version: 2
  build-image:
    jobs:
      - build:
          filters:
            branches:
              only: master
