export const actionTypes = {
  REQUEST_NEW_COMMENT: "REQUEST_NEW_COMMENT",
  REQUEST_NEW_COMMENT_FAILURE: "REQUEST_NEW_COMMENT_FAILURE",
  REQUEST_NEW_COMMENT_SUCCESS: "REQUEST_NEW_COMMENT_SUCCESS",

  REQUEST_COUPONS: "REQUEST_COUPONS",
  REQUEST_COUPONS_FAILURE: "REQUEST_COUPONS_FAILURE",
  REQUEST_COUPONS_SUCCESS: "REQUEST_COUPONS_SUCCESS",

  DELETE_COUPON: "DELETE_COUPON",
  DELETE_COUPON_FAILURE: "DELETE_COUPON_FAILURE",
  DELETE_COUPON_SUCCESS: "DELETE_COUPON_SUCCESS",
}